### ISSUE TITLE
Support of nvidia-docker2

### ISSUE THREAD

**Issue by diegoferigo** [diegoferigo/development-iit#1]
Nvidia-docker2 finally supports OpenGL :tada: 

I followed the procedure of the wiki and all worked smoothly with the new runtime.

```
dferigo@iiticublap110:~/git/development-iit/Tools$ docker info | grep Runtimes
Runtimes: nvidia runc
```

#### TODO

- [x] Test docker-compose with `runtime` option
- [x] Update `docker-workspace.sh`
- [x] Update Travis for building images from nvidia images

#### Resources

- https://devblogs.nvidia.com/gpu-containers-runtime/
- https://gitlab.com/nvidia/opengl/tree/ubuntu18.04
- https://hub.docker.com/r/nvidia/opengl/
- https://gitlab.com/nvidia/samples/blob/master/opengl/ubuntu16.04/glxgears/Dockerfile
- https://github.com/NVIDIA/nvidia-docker/issues/534#issuecomment-369657047
- http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration#nvidia-docker2
- https://github.com/lindwaltz/ros-indigo-desktop-full-nvidia/blob/master/Dockerfile

**Comment by diegoferigo** [comment]
Moved here from https://github.com/diegoferigo/dockerfiles/issues/15.
